generic:
  workspace: ./work
  job_command: ./a.out
  enabled_variable_name_argumentation: False

resource:
  type: local
  num_workers: 4

# ABCI:
#   group: your-group-id
#   job_execution_options: ""
#   job_script_preamble: |
#     #!/bin/bash

#     #$-l rt_C.small=1
#     #$-j y
#     #$-cwd

#     source /etc/profile.d/modules.sh
#     module load gcc/12.2.0
#     module load python/3.11

job_setting:
    job_timeout_seconds: 600
    max_failure_retries: 0
    trial_id_digits: 7

optimize:
  search_algorithm: aiaccel.optimizer.MOTpeOptimizer
  goal: [minimize, minimize]
  trial_number: 30
  rand_seed: 42
  parameters:
    -
      name: x1
      type: uniform_float
      lower: 0.0
      upper: 1.0
    -
      name: x2
      type: uniform_float
      lower: 0.0
      upper: 1.0
    -
      name: x3
      type: uniform_float
      lower: 0.0
      upper: 1.0
    -
      name: x4
      type: uniform_float
      lower: 0.0
      upper: 1.0
    -
      name: x5
      type: uniform_float
      lower: 0.0
      upper: 1.0
    -
      name: x6
      type: uniform_float
      lower: 0.0
      upper: 1.0
    -
      name: x7
      type: uniform_float
      lower: 0.0
      upper: 1.0
    -
      name: x8
      type: uniform_float
      lower: 0.0
      upper: 1.0
    -
      name: x9
      type: uniform_float
      lower: 0.0
      upper: 1.0
    -
      name: x10
      type: uniform_float
      lower: 0.0
      upper: 1.0
