cluster:
    _target_: distributed.Client
    address:
      _target_: dask_jobqueue.PBSCluster
      n_workers: 1
      processes: 8
      queue: "rt_HF"
      resource_spec: "select=1"
      job_extra_directives: ["-P gaa50073", "-j oe", "-k oed"]
      cores: 96
      memory: "1000GB"
      local_directory: "$TMPDIR"
      walltime: "02:00:00"
      scheduler_options: {interface: "ibn2"}
      job_script_prologue: ["cd $PBS_O_WORKDIR"]

params:
  _convert_: partial
  _target_: aiaccel.hpo.apps.optimize.HparamsManager
  x1:
    _target_: aiaccel.hpo.optuna.suggest_wrapper.SuggestFloat
    name: x1
    low: 0.0
    high: 1.0
    log: false
  x2:
    _target_: aiaccel.hpo.optuna.suggest_wrapper.SuggestFloat
    name: x2
    low: 0.0
    high: 1.0
    log: false

objective:
  _target_: objective.main

n_trials: 30
n_max_jobs: 4
