_base_: config.yaml

cluster:
    _target_: distributed.Client
    address:
      _target_: dask_jobqueue.PBSCluster
      n_workers: 1
      processes: 8
      queue: "rt_HF"
      resource_spec: "select=1"
      job_extra_directives: ["-P gaa50073", "-j oe", "-k oed"]
      cores: 96
      memory: "1000GB"
      local_directory: "$TMPDIR"
      walltime: "02:00:00"
      scheduler_options: {interface: "ibn2"}
      job_script_prologue: ["cd $PBS_O_WORKDIR"]
