[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "image_classification"
version = "0.0.0"
requires-python = ">=3.10"
dependencies = [
    "torchvision",
    "torchmetrics",
    "aiaccel"
]

# pixi configurations
[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
python = ">=3.10,<3.11"

[tool.pixi.pypi-dependencies]
image_classification = { path = ".", editable = true }

[tool.pixi.environments]
default = {features = []}

[tool.pixi.tasks]
