[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "image_classification"
version = "0.0.0"
requires-python = ">=3.10"
dependencies = [
    "torchvision",
    "torchmetrics",
    "aiaccel"
]