_base_:
  - ../resnet50.cifar10/config.yaml
n_gpus: 8

trainer:
  sync_batchnorm: true
  strategy:
    _target_: lightning.pytorch.strategies.DDPStrategy
    process_group_backend: "nccl"
    cluster_environment:
      _target_: aiaccel.torch.lightning.abci_environment.ABCIEnvironment

datamodule:
  batch_size: 256

task:
  optimizer_config:
    optimizer_generator:
      lr: 8.e-3
