study:
  _target_: optuna.create_study
  direction: minimize

  sampler:
    _target_: optuna.samplers.RandomSampler
    seed: null

params:
  _convert_: partial
  _target_: aiaccel.apps.optimize.HparamsManager
  x:
    _target_: aiaccel.apps.optimize.SuggestFloat
    name: x
    low: -10.0
    high: 10.0
    log: false

n_trials: 30
n_max_jobs: 4

group: gaa50000
