from __future__ import annotations

from torch.utils.data import SubsetRandomSampler

from aiaccel.nas.data_module.nas_dataloader import NAS1shotDataLoader


class SubsetRandomSamplingDataLoader(NAS1shotDataLoader):
    """A data loader for 1 shot NAS with SubsetRandomSampling."""

    _supernet_train_data_indices: list[int]
    _architecture_search_data_indices: list[int]
    _sampler_supernet_train: SubsetRandomSampler
    _sampler_architecture_search: SubsetRandomSampler

    def _create_sampler(self) -> None:
        """Load SubsetRandomSamplers for supernet train and architecture search dataloader.

        _supernet_train_data_indices and _architecture_search_data_indices are required for SubsetRandomSampling.
        These indices are generated by get_random_indices().
        """
        self._sampler_supernet_train = SubsetRandomSampler(self._supernet_train_data_indices)
        self._sampler_architecture_search = SubsetRandomSampler(self._architecture_search_data_indices)
