name: CI

on:
  push:
    branches: ["main", "develop/*"]
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-22.04"]
        python-version: ["3.10"]
        test_target: ["config", "hpo", "torch"]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: prefix-dev/setup-pixi@v0.9.6
        with:
          environments: gh-actions
      - name: Run pytest
        run: |
          pixi run -e gh-actions pytest -v \
            -n auto \
            --cov=aiaccel/${{ matrix.test_target }} \
            --cov-branch \
            --cov-append \
            --cov-report=term-missing \
            tests/${{ matrix.test_target }}
  ci-job-local:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-22.04"]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: prefix-dev/setup-pixi@v0.9.6
        with:
          environments: gh-actions
      - name: Run pytest
        run: |
          pixi run -e gh-actions pytest -v \
            -n auto \
            --cov=aiaccel/job/apps \
            --cov-branch \
            --cov-append \
            --cov-report=term-missing \
            tests/job/apps/local.py
