name: Validate code formats.
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort pycodestyle

      - name: Pycodestyle Test
        run: pycodestyle --max-line-length=120 aiaccel examples

      - name: Lint
        run: |
          flake8 --max-line-length 120 aiaccel
          isort --check --diff aiaccel
          black --check --line-length 120 aiaccel