name: Lint

on:
  push:
    branches: ["main", "develop/*"]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04']
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: prefix-dev/setup-pixi@v0.9.5
        with:
          manifest-path: pyproject.toml
          pixi-version: v0.66.0
          cache: true
          activate-environment: false
          environments: gh-actions
      - name: Perform ruff
        run: |
          pixi run -e gh-actions ruff check
          pixi run -e gh-actions ruff format --check
      - name: Perform mypy
        run: |
          pixi run -e gh-actions mypy --config-file mypy.ini . --explicit-package-bases
      - name: Perform docstrfmt
        run: |
          pixi run -e gh-actions docstrfmt --check docs/source/
