name: Check code formating
on: [push, pull_request]

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  ruff:
    steps:
      - name: Perform ruff
        run: |
          ruff check 
          ruff format --check
