name: CI
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        python-version: ['3.10']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Install Software
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev,github-actions,test]

      - name: Unit Test
        run: pytest -v --cov=aiaccel --cov-branch --cov-report=term-missing tests/apps/
